name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm install --force

      - name: Run Lint
        run: npm run lint

      - name: Run Node.js Tests
        run: npm test  # Asumiendo que tienes pruebas configuradas aquí

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Chrome Driver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies for Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium Tests
        run: |
          python test_login_guest.py
          python test_vista_users.py

      - name: Build
        run: npm run build

      - name: List output files
        run: ls -l dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
